version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - checkout
          name: Install ospd from Github master
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install https://github.com/greenbone/ospd/archive/master.zip
      - run:
          name: Install OSPD-DEBSECAN
          command: |
            . venv/bin/activate
            pip install .
  test:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install coverage.py and codecov
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install coverage codecov
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            coverage run -m unittest
      - run:
          name: Upload coverage to Codecov
          command: |
            . venv/bin/activate
            codecov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

